sharerich.set.*:
  type: config_entity
  label: 'Sharerich set'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    services:
      type: sequence
      label: 'Enabled services'
      sequence:
        - type: sequence
          sequence:
            - type: string
