sharerich.sharerich.*:
  type: config_entity
  label: 'Sharerich config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    services:
      type: sequence
      label: 'Enabled services'
    uuid:
      type: string
