sharerich.settings:
  type: mapping
  label: Settings
  mapping:
    allowed_html:
      type: string
    facebook_app_id:
      type: string
    facebook_site_url:
      type: string
    youtube_username:
      type: string
    github_username:
      type: string
    instagram_username:
      type: string
    twitter_user:
      type: string

sharerich.sharerich.*:
  type: config_entity
  label: 'Sharerich config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    create_block:
      type: boolean
      label: 'Create a block for this button set'
    block_title:
      type: string
      label: 'Block title'
    services:
      type: sequence
      label: 'Enabled services'
    uuid:
      type: string
